codesupport/website-frontend

README.md
components/molecules/CardGroup.js
components/molecules/Dropdown.js
components/molecules/Navigation.js
components/molecules/OpenSourceProjects.js
components/molecules/SearchBar.js
config.json
lib/fetchResources.js
package-lock.json
package.json
pages/resources.js

This PR adds the functionality for the resources page. It also adds the CS icon to the navigation menu.

Resources page

---

src/components/molecules/Navigation.js
src/components/templates/Container.js
src/pages/discord-rules.js
src/styles/style.css

- Added Discord Rules Page
- Updated `<Container />` to accept a margin prop
- Changed `<Navigation />` to have a shadow so it doesn't look so dull on blank pages

Discord Rules Page

---

.firebaserc
.github/workflows/deploy.yml
firebase.json
package.json

**Please merge #10 first.**
- Added a new NPM script to export the site
- Added a new CI workflow to deploy the site

Setup CI workflow to deploy site on merge to master.

---

src/lib/fetchResources.js

Added alphabetical sorting to resources

---

README.md
package-lock.json
package.json
src/pages/_app.js
src/services/FirebaseService.js

- Installed Firebase SDK
- Setup Firebase Analytics
- Setup Firebase Performance Monitoring

Setup Firebase Analytics and Performance

---

README.md
package-lock.json
package.json
src/helpers/getQueryParams.js
src/pages/_app.js
src/pages/resources.js
src/services/FirebaseService.js

**Merge #14 First**
- Added a helper function to get query parameters
- Wrapped `<Resources />` in a HOC so that we can use the `useRouter()` hook in a class
- Added support so that you can filter resources via the `?categories` query parameter

Resources category filter param

---

.eslintrc.js
package-lock.json
package.json
src/components/molecules/index/WhyJoinCodeSupport.js
src/components/organisms/Columns.js
src/pages/index.js

- Updated ESLint rules to allow wrapping components in `()`
- Installed solid Font Awesome Icons
- Added `<Columns />` to generate a three-column layout
- Added `<WhyJoinCodeSupport />`

Added "Why Join CodeSupport" Section

---

.github/workflows/deploy.yml
src/components/organisms/Columns.js

I've fixed the heading size so that it is a `<h3>` and disabled the daily deploy because it's useless currently.

Fix Heading Size & Disable Daily Deploy

---

src/pages/resources.js

gg ezy
- Made the filters be more spaced out
- Changed some formatting and re-organised imports

Space out filters better and fix some formatting.

---

.github/scripts/generate-sitemap.js
.github/workflows/deploy.yml
package-lock.json
package.json

Google WebMasters suggested we add one, this generates one on deploy.

Generate sitemap on deploy.

---

firebase.json

Allow sharing of the leaderboard easily.

Added redirect for advent of code.

---

package-lock.json
package.json
src/components/molecules/Dropdown.js
src/components/molecules/SearchBar.js
src/pages/resources.js

Fixed the bug. 
The problem was that when filtering for filter A you would just request resources for filter A's conditions and ignore if the resource had filter B's conditions as well and vice versa.

fixed article previewer bug

---

.github/workflows/deploy.yml
src/components/molecules/index/WhyJoinCodeSupport.js
src/pages/article-previewer.js
src/services/FirebaseService.js

- Added back nightly deploys for resources and articles
- Show what has been added in deploy messages
- Fixed React errors regarding keys
- Don't use prod Firebase credentials on localhost

Tidy Up of Code

---

.github/workflows/deploy.yml
src/components/templates/PageTemplate.js
src/services/FirebaseService.js

- Made images be the correct size for the context
- Changed Firebase environment to development in preview channels
- Stopped nightly cron message because it's annoying

Fixed Images & Stopped Nightly Deploy Message

---

src/config.json

Hope you had a good christmas 💜. Sorry for taking so long since my commit to the resources repo.

Add java to resource categories

---

src/pages/_app.js

Revert cors changes

---

src/components/organisms/LoginForm.js
src/components/organisms/ProfileHeader.js
src/lib/fetchProfiles.js
src/pages/article/[path].js
src/pages/profile/[alias].js
src/services/ArticleService.js
src/services/UserService.js

- Very basic profile page
- Updated Article rich meta to be more in-depth for the creator
- Updated `UserService` with methods for user and profile

Basic profile page.

---

src/components/molecules/Card.js
src/components/molecules/URLCard.js
src/components/molecules/index/OpenSourceProjects.js
src/pages/articles.js
src/pages/resources.js

URLCard component wraps around the Card component which makes the whole card clickable instead of a small text button
- Added URLCard component
- Changed hover effect to a slightly darker box-shadow (can be changed ofcourse)
- Changed the Card items on home, resources and articles to URLCard items

Creates a clickable card component URLCard for articles/resources

---

src/components/atoms/Button.js
src/components/molecules/ShareButtons.js
src/pages/article/[path].js

Allows users to easily share articles to Twitter and Reddit.

Share Article Buttons

---

src/components/atoms/Alert.js
src/components/organisms/LoginForm.js

Implements #49
(screenshot taken on chrome for macOS)

Added alert component

---

src/components/molecules/Navigation.js

Resolves #56 
Changes the cursor from being the default to a `pointer` since it is a link.

Make navigation logo have a pointer cursor.

---

src/pages/article/[path].js

This was previously trying to pull description from the article whereas description is part of the revision stored within an article.

Description is part of the revision

---

README.md

Adding some text about how you may need to have a local version of the backend running for some functionality to work.

Add note about using Backend

---

.gitignore
README.md
package-lock.json
package.json
src/components/molecules/Navigation.js
src/components/templates/ProtectedPageTemplate.js
src/pages/_app.js
src/pages/profile/index.js
src/styles/style.css

- Setup Auth0 to handle authorisation
- Updated the `<ProtectedPageTemplate />` to use Auth0
- Updated the navigation in line with the new designs to use data from Auth0

Setup Auth0 & New Navigation

---

README.md
package-lock.json
src/hooks/useAPI.js
src/pages/_app.js
src/pages/profile/index.js

Created a new `useAPI` hook which takes a method, route and optionally a body to send to the API via an authenticated request.

useAPI Hook

---

.github/workflows/deploy.yml

Re-enabling nightly and on merge deployments.

Re-enable Deployments

---

src/data/articles/how-i-got-a-job-after-university-during-the-pandemic.md
src/data/articles/how-to-kill-the-firestore-emulator.md

Two articles had incorrect descriptions - this resolves that.

Correct Article Descriptions

---

.github/scripts/generate-sitemap.js
src/components/templates/PageTemplate.js

Fixing some issues raised by Google Search Console:
- Duplicate without user-selected canonical
- Page with redirect

Issues rasied by Search Console

---

src/data/articles/how-to-solve-conflicts-in-package-yarn-lock-files.md

A short article on how to solve conflicts within programatically generated lock files.

Article: 'How To Solve Conflicts In Package/Yarn Lock Files'

---

firebase.json

Update Advent of Code URL

---

src/components/molecules/Card.js
src/components/organisms/Columns.js

**- Shrunk the size of the FA icon.**
They were too big, inconstant and out of place.
**- Centered text.**
The centered text compliments the centered FA icon
**- Added border, border radius and background.**
This matches the theme of the "We Love Open Source" section. 
**- Stopped the last card from being hidden while on mobile.**
The third card was being removed for no reason when the screen width was below 800px.

Improved Columns on Index

---

.github/CONTRIBUTING.md

Copied this over from the Discord Bot and edited where necessary.

Add Contributing Guidelines

---

README.md

Removing the discriminator in the README since Discord no longer uses them.

Remove Discriminator

---

src/data/articles/beginners-guide-to-programming.md
src/data/articles/on-completion.md

Article was written earlier, just adds it

Adding beginners guide to programming

---

src/data/articles/beginners-guide-to-programming.md

Making the links clickable so that they are easier to visit for users reading the article.

Make Links In Article Clickable

---

.github/workflows/deploy.yml
.github/workflows/main.yml

Reverts codesupport/website-frontend#125

Revert "Deploy to Firebase Hosting Preview Channels"

---

.github/workflows/deploy.yml
next.config.js

This works differently now, my bad
https://nextjs.org/docs/pages/building-your-application/deploying/static-exports

Fix deployment

---

.github/ISSUE_TEMPLATE/bug.MD
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature.md

closes #139 
Hello:)
I have added the issue template files.

Issue Templates

---

src/components/molecules/Footer.tsx

Fix issue #146: Enlarge bottom text

Fix issue #146: Enlarge bottom text

---

src/components/molecules/NavigationMobile.tsx

Added visible active state on the nav mobile labels when visiting the pages, and changed the label color to black when hovering on low screens as you could not clearly see it before.
[screen-capture.webm](https://github.com/user-attachments/assets/728787ad-bde5-4500-baee-75de353da38a)

Added active state for mobile nav and changed UI state when hovering 

---

firebase.json

Another year, another challenge I will give up on after three days.

Update Advent of Code URL Year
